export const CHARACTERS_DATA_REQUEST = 'CHARACTERS_DATA_REQUEST';
export const CHARACTERS_DATA_RESPONSE = 'CHARACTERS_DATA_RESPONSE';
export const CHARACTERS_DATA_FAILED = 'CHARACTERS_DATA_FAILED';

export const CHARACTER_REQUEST = 'CHARACTER_REQUEST';
export const CHARACTER_RESPONSE = 'CHARACTER_RESPONSE';
export const CHARACTER_FAILED = 'CHARACTER_FAILED';

export const EPISODES_DATA_REQUEST = 'EPISODES_DATA_REQUEST';
export const EPISODES_DATA_RESPONSE = 'EPISODES_DATA_RESPONSE';
export const EPISODES_DATA_FAILED = 'EPISODES_DATA_FAILED';

export const EPISODE_REQUEST = 'EPISODE_REQUEST';
export const EPISODE_RESPONSE = 'EPISODE_RESPONSE';
export const EPISODE_FAILED = 'EPISODE_FAILED';

export const CHARACTERS_SET_PAGES_COUNT = 'SET_PAGES_COUNT';
export const CHARACTERS_SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';

export const EPISODES_SET_PAGES_COUNT = 'EPISODES_SET_PAGES_COUNT';
export const EPISODES_SET_CURRENT_PAGE = 'EPISODES_SET_CURRENT_PAGE';
