export const CHARACTERS_DATA_REQUEST = 'CHARACTERS_DATA_REQUEST';
export const CHARACTERS_DATA_RESPONSE = 'CHARACTERS_DATA_RESPONSE';
export const CHARACTERS_DATA_FAILED = 'CHARACTERS_DATA_FAILED';

export const EPISODES_DATA_REQUEST = 'EPISODES_DATA_REQUEST';
export const EPISODES_DATA_RESPONSE = 'EPISODES_DATA_RESPONSE';
export const EPISODES_DATA_FAILED = 'EPISODES_DATA_FAILED';

export const SET_PAGES_COUNT = 'SET_PAGES_COUNT';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
